In [2]:
import cv2
import random
import numpy as np
from matplotlib import pyplot as plt

cv2.startWindowThread()
img_gray = cv2.imread('lenna.jpeg', 0)
cv2.imshow('lenna', img_gray)
key = cv2.waitKey()
if key == 27:  # if 'esc' is pressed
    cv2.destroyAllWindows()
    cv2.waitKey(1)

27


In [3]:
print(img_gray)

[[139 138 135 ...  99  95 100]
 [138 137 135 ...  98  94  98]
 [136 135 133 ...  97  94  95]
 ...
 [113 122 132 ...  48  48  50]
 [113 122 132 ...  47  49  51]
 [106 117 130 ...  46  49  50]]


In [4]:
print(img_gray.dtype)

uint8


In [5]:
print(img_gray.shape)

(225, 225)


In [6]:
img = cv2.imread('lenna.jpeg')
cv2.imshow('lenna', img)
key = cv2.waitKey()
if key == 27:  # if 'esc' is pressed
    cv2.destroyAllWindows()
    cv2.waitKey(1)

In [7]:
print(img)

[[[ 88 118 201]
  [ 87 117 200]
  [ 82 113 198]
  ...
  [ 58  83 147]
  [ 54  79 143]
  [ 61  81 152]]

 [[ 87 117 200]
  [ 86 116 199]
  [ 82 113 198]
  ...
  [ 57  82 146]
  [ 53  78 142]
  [ 61  80 148]]

 [[ 85 115 198]
  [ 84 114 197]
  [ 80 111 196]
  ...
  [ 58  81 143]
  [ 55  78 140]
  [ 61  78 141]]

 ...

 [[ 58  93 173]
  [ 67 103 181]
  [ 79 114 188]
  ...
  [ 34  39  72]
  [ 36  38  72]
  [ 41  41  71]]

 [[ 58  93 173]
  [ 67 103 181]
  [ 79 114 188]
  ...
  [ 33  38  71]
  [ 35  40  71]
  [ 42  43  71]]

 [[ 49  85 169]
  [ 62  96 179]
  [ 77 110 189]
  ...
  [ 41  37  66]
  [ 45  40  69]
  [ 39  41  71]]]


In [8]:
print(img.shape)

(225, 225, 3)


In [9]:
B, G, R = cv2.split(img)
cv2.imshow('B', B)
cv2.imshow('G', G)
cv2.imshow('R', R)
key = cv2.waitKey()
if key == 27:  # if 'esc' is pressed
    cv2.destroyAllWindows()
    cv2.waitKey(1)

In [11]:
img_crop = img[0:100, 0:100]
cv2.imshow('img_crop', img_crop)
key = cv2.waitKey()
if key == 27:  # if 'esc' is pressed
    cv2.destroyAllWindows()
    cv2.waitKey(1)

In [ ]:
def crop(img):

In [ ]:
def random_light_color(img):

In [ ]:
def adjust_gamma(img, gamma):